jwt:
  header: Authorization
  # This token must be encoded using Base64 with mininum 88 Bits (you can type `echo 'secret-key'|base64` on your command line)
  base64-secret: QTNKYU5kUmdVa1huMnI1dTd4IUE/RCZHK0tiUGVTaFZtWXEzc1Fkdjl5JEImRUVyQE1jUWZUaldwOWhyNHU3dyF6JUMqQS1KMlRtZG52c1hwMnM1djh5Lz9EKEcrS2JQZVNoVm1ZcTN0Nnc5eiRDJkVPSEFNY1FmVGpXblpyNHU3
  # token is valid 24 hours
  token-validity-in-seconds: 86400
  route:
    authentication:
      path: auth
      refresh: refresh

spring:
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 2
    database: mysql
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true

  # Data base properties
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/cloud?useSSL=false&zeroDateTimeBehavior=convertToNull&noAccessToProcedureBodies=true&sessionVariables=wait_timeout=600&serverTimezone=Asia/Seoul"
    username: "root"
    password: "1234"